version: '3.1'

services:
  
  database:
    image: postgres:14.3
    restart: always
    env_file:
      - .env    
    ports:
      - "5432:5432"
    environment:
      POSTGRESS_PASSWORD: ${POSTGRES_PASSWORD} 
      POSTGRESS_DB: ${POSTGRES_DB}
    volumes:
      - ./postgress_data:/var/lib/postgress/data