version: '3.1'

services:
  database:
    image: mongo:5
    restart: always
    ports:
      - 27018:27017
    environment:
      - MONGODB_DATABASE=businesses_database
    volumes:
      - ./db_volume:/data/db